### PR TITLE
Adds Bazel macros, Python CLI, and basic workflow tests.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
An unfortunately large initial PR.

Per f2f with @sammy-tri, will work on adding in Travis CI and linting.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/1)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@sammy-tri for feature review, please.

---

Review status: 0 of 73 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-:-L0owtOsJJgfHcu4khMY:bp6jcp0)*

**Comment by sammy-tri** [comment]
Checkpoint, slowly working my way through.  (apologies for the delay)

---

Reviewed 14 of 73 files at r1.
Review status: 14 of 73 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tiE7uOUu4FtL0S764:-L0tiE7vEDI2Bj7WkIEl:b79ctep) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/README.md#L3)):*
> ```Markdown
> # About
> 
> This is a Bazel-focused implementation for incorporating external data into the workspace (not to be versioned in Git, etc.) for testing and running binaries.
> ```

BTW perhaps this could be a bit more clear?  I feel like the goal is that there is versioning for the file provided by the hash, but the data is not stored in git.

---

*[docs/setup.md, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tYE_phRu3QGgg_CgO:-L0tYE_phRu3QGgg_CgP:bdpk5fb) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/setup.md#L5)):*
> ```Markdown
> ## Prerequisites
> 
> For a basic client, you must base `python` and the `girder_client` installed.
> ```

I'm not sure what "you must base" means..

---

*[docs/setup.md, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tYrPnziAZOWFv76Wd:-L0tYrPpUUp69dE-Duk6:b-iztvu4) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/setup.md#L33)):*
> ```Markdown
> 
> * Inspect the configuration examples in `docs/config`:
>     * `external_data.user.yml` - Copy this to `~/.config/bazel_external_data/config.yml`
> ```

Is it possible (or already the case) to make this optional if the user isn't going to upload?  (my motivation here is so that something like `git clone https://RobotLocomotion/drake.git && cd drake && sudo ./setup/ubuntu/16.04/install_prereqs.sh && bazel build //...` will "just work" without any additional configuration (as I think is the case now).)

---

*[docs/workflows.md, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tZb-Wo8jj9ZcgBP3e:-L0tZb-Wo8jj9ZcgBP3f:bltizo4) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L14)):*
> ```Markdown
>         http_archive(
>             name = "bazel_external_data_pkg",
>             url = "https://github.com/EricCousineau-TRI/bazel_external_data/archive/ce71398ac319cf4dedcf3eed3ae5c2c25e4eb1b4.zip",
> ```

Perhaps update the repo from EricCousineau-TRI to RobotLocomotion?

---

*[docs/workflows.md, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tcU-qeNe8hyiFjwCs:-L0tcU-r3jIsDL4KuuLZ:b-5mugl7) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L34)):*
> ```Markdown
> 3. Under `${workspace}/tools`:
> 
>     1. Add `BUILD` (to enable it as a package).
> ```

I'm not sure I'd be able to follow this instruction.  Does this just mean "make sure there's a `BUILD` (or `BUILD.bazel`) file present in the `tools` directory at all?

---

*[docs/workflows.md, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tcsCdSeV90KPy8225:-L0tcsCdSeV90KPy8226:bkod96l) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L70)):*
> ```Markdown
>         load("//tools:external_data.bzl",
>             "external_data",
>             "external_data_group",
> ```

Do you actually need to `load` all three of these if you're only calling `external_data`?

---

*[docs/workflows.md, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0td0Zot1BwJaTMz5vp:-L0td0Zp0tUqUwhNXQtP:b9cfb69) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L102)):*
> ```Markdown
> 
>         cd data
>         touch dragon.obj
> ```

Why is the 'touch' needed?

---

*[docs/workflows.md, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tdKeX0B2K1Z3LlQ0o:-L0tdKeX0B2K1Z3LlQ0p:b-1vmbx3) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L117)):*
> ```Markdown
> 3. To test if Bazel can download this file, execute this in `:/data`:
> 
>         bazel build :dragon.obj
> ```

Where does this file wind up after this operation?  `bazel-bin` somewhere?  (I know I tested this workflow so I probably knew the answer once, but I can't remember)

---

*[tools/macros.bzl, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0thAeuG3bRBDVYu_cB:-L0thAevud85YXauWtcU:b-552522) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/tools/macros.bzl#L62)):*
> ```Python
>         'no_cache' - Download the file, do not use the cache.
>     @param settings
>         Settings for the given repository (or even individual target).
> ```

Wouldn't any settings passed to `external_data` be for an individual target by definition?  Or have I misunderstood something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-:-L0tiZewHJoPlXNstniU:b-gqiynh)*

**Comment by EricCousineau-TRI** [comment]
Review status: 10 of 72 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tiE7uOUu4FtL0S764:-L1-91EEfoLvWTD4dA8t:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/README.md#L3)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW perhaps this could be a bit more clear?  I feel like the goal is that there is versioning for the file provided by the hash, but the data is not stored in git.
</blockquote></details>

Done.

---

*[docs/setup.md, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tYE_phRu3QGgg_CgO:-L1-92FwQozZVjjYs7Cn:b-tgelyg) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/setup.md#L5)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure what "you must base" means..
</blockquote></details>

Done. (Also, removed Girder stuff - will add that in subsequent PR, once base structure is good to go.)

---

*[docs/setup.md, line 33 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tYrPnziAZOWFv76Wd:-L1-96jPdrda51pBIFdq:b-95hpjk) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/setup.md#L33)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is it possible (or already the case) to make this optional if the user isn't going to upload?  (my motivation here is so that something like `git clone https://RobotLocomotion/drake.git && cd drake && sudo ./setup/ubuntu/16.04/install_prereqs.sh && bazel build //...` will "just work" without any additional configuration (as I think is the case now).)
</blockquote></details>

Done. This is mentioned below, and I will ensure that this is part of a Girder test.

---

*[docs/workflows.md, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tZb-Wo8jj9ZcgBP3e:-L1-9Dpahepn2gxYgUdR:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L14)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Perhaps update the repo from EricCousineau-TRI to RobotLocomotion?
</blockquote></details>

Done.

---

*[docs/workflows.md, line 34 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tcU-qeNe8hyiFjwCs:-L1-9EUozmCOwFVSBgvc:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L34)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm not sure I'd be able to follow this instruction.  Does this just mean "make sure there's a `BUILD` (or `BUILD.bazel`) file present in the `tools` directory at all?
</blockquote></details>

Done.

---

*[docs/workflows.md, line 70 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tcsCdSeV90KPy8225:-L1-9F2fBZreUj985LlP:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L70)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Do you actually need to `load` all three of these if you're only calling `external_data`?
</blockquote></details>

Done.

---

*[docs/workflows.md, line 102 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0td0Zot1BwJaTMz5vp:-L1-9F_GV8rf0SOiumu3:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L102)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Why is the 'touch' needed?
</blockquote></details>

Done.

---

*[docs/workflows.md, line 117 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0tdKeX0B2K1Z3LlQ0o:-L1-9GeRUBWfd4ef1Vu6:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/docs/workflows.md#L117)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Where does this file wind up after this operation?  `bazel-bin` somewhere?  (I know I tested this workflow so I probably knew the answer once, but I can't remember)
</blockquote></details>

Done.

---

*[tools/macros.bzl, line 62 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0thAeuG3bRBDVYu_cB:-L1-9I7lKhX7EOg4IWCy:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/tools/macros.bzl#L62)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Wouldn't any settings passed to `external_data` be for an individual target by definition?  Or have I misunderstood something?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1)*

**Comment by sammy-tri** [comment]
commit some more comments I forgot to submit before break

---

Reviewed 2 of 73 files at r1.
Review status: 12 of 72 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/bazel_external_data/BUILD.bazel, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0yw-9U6GHHJlTT7x9e:-L0yw-9V62PowkSqY_Nb:b-two1p9) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/src/bazel_external_data/BUILD.bazel#L1)):*
> ```Python
> # @note 'core' has no backends present.
> ```

Putting `# -*- python -*- ` on the first line of the BUILD.bazel files (as drake does) would be convenient for those whose editors recognize that tag

---

*[src/bazel_external_data/BUILD.bazel, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0yxjdX5iMVCNmSHtDP:-L0yxjdYnQm12iPwxWHT:b6yxg97) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/src/bazel_external_data/BUILD.bazel#L10)):*
> ```Python
>         "hashes.py",
>     ],
>     imports = [".."],
> ```

This looks strange enough that it probably deserves a comment.

---

*[src/bazel_external_data/config_helpers.py, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0yyHP4uUfGRgVpiOTb:-L0yyHP5yIQ0Lfl6DkSt:bmyhiqf) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/src/bazel_external_data/config_helpers.py#L15)):*
> ```Python
> 
> 
> def guess_start_dir(filepath):
> ```

It's not obvious why a function with this behavior has the name `guess_start_dir`

---

*[src/bazel_external_data/util.py, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L1rYHYqNWXteAYBQ_Ho:-L1rYHYrEPLeyCx0ZjIL:b-ulgjvq) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/src/bazel_external_data/util.py#L75)):*
> ```Python
>     cur_dir = start_dir
>     assert len(cur_dir) > 0
>     for i in xrange(max_depth):
> ```

BTW I don't think our style guide mandates this, but I personally like using `_` (as opposed to `i` here) to indicate that I'm deliberately declaring an unused variable in python.  Alternately a comment that `i` is deliberately unused might be nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-:-L1rYkvaL9B-WlR7RL1P:b-lr754y)*

**Comment by sammy-tri** [comment]
Reviewed 4 of 5 files at r2.
Review status: 16 of 72 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1)*

**Comment by EricCousineau-TRI** [comment]
Review status: 12 of 72 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/bazel_external_data/BUILD.bazel, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0yw-9U6GHHJlTT7x9e:-L1soiq78dbH_DHIGX3N:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/src/bazel_external_data/BUILD.bazel#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Putting `# -*- python -*- ` on the first line of the BUILD.bazel files (as drake does) would be convenient for those whose editors recognize that tag
</blockquote></details>

Done.

---

*[src/bazel_external_data/BUILD.bazel, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0yxjdX5iMVCNmSHtDP:-L1sojB-ELovATesfTZ4:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/src/bazel_external_data/BUILD.bazel#L10)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

This looks strange enough that it probably deserves a comment.
</blockquote></details>

Done.

---

*[src/bazel_external_data/config_helpers.py, line 15 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L0yyHP4uUfGRgVpiOTb:-L1sojshNFVdn9_T5QHI:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/src/bazel_external_data/config_helpers.py#L15)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It's not obvious why a function with this behavior has the name `guess_start_dir`
</blockquote></details>

Done.

---

*[src/bazel_external_data/util.py, line 75 at r1](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L1rYHYqNWXteAYBQ_Ho:-L1sokqMIApHukLxS2qO:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/b77bd8af48c83f4073c4b1070a71775ab2e6a1c0/src/bazel_external_data/util.py#L75)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I don't think our style guide mandates this, but I personally like using `_` (as opposed to `i` here) to indicate that I'm deliberately declaring an unused variable in python.  Alternately a comment that `i` is deliberately unused might be nice
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1)*

**Comment by sammy-tri** [comment]
Still working through, sorry for how long this is taking me (I've needed a few breaks).  Is this the right place to have the conversation about this code being standalone vs. living inside drake?

---

Reviewed 10 of 73 files at r1, 7 of 14 files at r3.
Review status: 29 of 72 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/bazel_external_data/check.py, line 3 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21p5e4Y832RSY9OorZ:-L21p5e5hFITjldm-THI:b-flj539) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/check.py#L3)):*
> ```Python
> """
> @file
> Allows uploading data file to a remote.
> ```

Is this file level comment accurate?

---

*[src/bazel_external_data/cli.py, line 38 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21pNwe61LXayY9HmHf:-L21pNwfaJHG7HwNSY5h:bnmz7rt) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/cli.py#L38)):*
> ```Python
> args = parser.parse_args()
> 
> # Do not allow running under Bazel unless we have a guess for the project root from an input file.
> ```

long line (one of many in this file)

---

*[src/bazel_external_data/core.py, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21n3ZY0L5Oy1Y3awKA:-L21n3ZZMcmd0EBCHtM_:b-t22abr) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/core.py#L8)):*
> ```Python
> 
> PROJECT_CONFIG_FILE = ".external_data.yml"
> USER_CONFIG_FILE_DEFAULT = os.path.expanduser("~/.config/bazel_external_data/config.yml")
> ```

https://www.python.org/dev/peps/pep-0008/#maximum-line-length

---

*[src/bazel_external_data/download.py, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21oHwnrqawxSIEzWq5:-L21oHwnrqawxSIEzWq6:bc9cmhy) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/download.py#L1)):*
> ```Python
> from __future__ import absolute_import, print_function
> ```

Are either of these used?

---

*[src/bazel_external_data/download.py, line 2 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21oKYUFw42XSEkQvyT:-L21oKYUFw42XSEkQvyU:b-jmepyd) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/download.py#L2)):*
> ```Python
> from __future__ import absolute_import, print_function
> import argparse
> ```

unused

---

*[src/bazel_external_data/hashes.py, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21lnk4lCB1gQ3RMMys:-L21lnk5yda5ZRElsloE:b7zfzpz) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/hashes.py#L5)):*
> ```Python
> 
> 
> class HashType(object):
> ```

BTW consider naming `_HashType` if it's not used outside of this file?

---

*[src/bazel_external_data/hashes.py, line 116 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21m-55QIjPNiOB4BQ3:-L21m-55QIjPNiOB4BQ4:b-1nc5zy) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/hashes.py#L116)):*
> ```Python
> sha512 = Sha512()
> 
> if __name__ == "__main__":
> ```

Is this code automatically invoked anywhere as a test or something?  My inclination is to comment why it's here or just delete it if it's never executed to avoid bitrot.

---

*[src/bazel_external_data/upload.py, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21oQSDsrdfc0tquHIZ:-L21oQSEVwuEOx_sidf7:buzc58k) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/upload.py#L1)):*
> ```Python
> from __future__ import absolute_import, print_function
> ```

unused?

---

*[src/bazel_external_data/upload.py, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21oR8k9i8YYNvqHc6j:-L21oR8lD-Lm351_krt9:b-jmepyd) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/upload.py#L5)):*
> ```Python
> import os
> import sys
> import argparse
> ```

unused

---

*[src/bazel_external_data/upload.py, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21ox2n__8x491PRUq6:-L21ox2oOfkNXvdO47Gm:bt3r69v) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/upload.py#L9)):*
> ```Python
> from bazel_external_data import core, util
> ```

BTW I think both this file and`download.py` would benefit from a file level comment explaining what their purpose is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-:-L21qJI8SOxJHrHz3CCp:b-3ygfv0)*

**Comment by EricCousineau-TRI** [comment]
Yes, I think it would be.
Per our f2f, I was going to move this into `tools/third_party` most likely, as I want it to be a separate workspace still.

The only remaining item would be to, at some point, ensure that unittests using Girder via docker can be included; Jeremy's mentioned that in RobotLocomotion/drake#7654.

---

Review status: 29 of 72 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-:-L26rVnXNuJwDBec3sJN:bckg15h)*

**Comment by sammy-tri** [comment]
Reviewed 1 of 73 files at r1, 1 of 14 files at r3.
Review status: 31 of 72 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1)*

**Comment by EricCousineau-TRI** [comment]
Review status: 25 of 72 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/bazel_external_data/check.py, line 3 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21p5e4Y832RSY9OorZ:-L2MN4rHI4S4Ec4DEmLH:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/check.py#L3)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this file level comment accurate?
</blockquote></details>

Done.

---

*[src/bazel_external_data/cli.py, line 38 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21pNwe61LXayY9HmHf:-L2MNLaw2eh5GwcJK4ui:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/cli.py#L38)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

long line (one of many in this file)
</blockquote></details>

Done.

---

*[src/bazel_external_data/core.py, line 8 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21n3ZY0L5Oy1Y3awKA:-L2MNMIvfXn1vvXw4q5c:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/core.py#L8)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

https://www.python.org/dev/peps/pep-0008/#maximum-line-length
</blockquote></details>

Done.

---

*[src/bazel_external_data/download.py, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21oHwnrqawxSIEzWq5:-L2MNN9L5W1_-Hdv0tdA:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/download.py#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Are either of these used?
</blockquote></details>

Done.

---

*[src/bazel_external_data/download.py, line 2 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21oKYUFw42XSEkQvyT:-L2MNNVXSxNWEwwcYN8V:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/download.py#L2)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

---

*[src/bazel_external_data/hashes.py, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21lnk4lCB1gQ3RMMys:-L2MNO_SIC-nL-cVX1rg:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/hashes.py#L5)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW consider naming `_HashType` if it's not used outside of this file?
</blockquote></details>

Done.

---

*[src/bazel_external_data/hashes.py, line 116 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21m-55QIjPNiOB4BQ3:-L2MNP6Vd6-HMPC85TcW:br9bpt1) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/hashes.py#L116)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is this code automatically invoked anywhere as a test or something?  My inclination is to comment why it's here or just delete it if it's never executed to avoid bitrot.
</blockquote></details>

Done. Removed, it was just a little test as I was prototyping.

---

*[src/bazel_external_data/upload.py, line 1 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21oQSDsrdfc0tquHIZ:-L2MNUL02Cu7Pg7OAdqZ:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/upload.py#L1)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.

---

*[src/bazel_external_data/upload.py, line 5 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21oR8k9i8YYNvqHc6j:-L2MNUlyIpDftBDH92E_:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/upload.py#L5)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

---

*[src/bazel_external_data/upload.py, line 9 at r3](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1#-L21ox2n__8x491PRUq6:-L2MNVBScA01z8Y99Em1:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/ae4f641c3682f10eb3854613c3f5f835136d693e/src/bazel_external_data/upload.py#L9)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

BTW I think both this file and`download.py` would benefit from a file level comment explaining what their purpose is
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bazel-external-data/1)*

**Comment by EricCousineau-TRI** [comment]
Closing for now.

**Pull request closed without merging**
