### PR TITLE
Add logging for retry failures

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@IanTheEngineer This is the code I am using to generate usable debugging info for Ramya.  It's not high priority to land since I can repro the failures locally with a local repo override, but will want to have it eventually.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-:-O6vLDqMCIfkQfjuVShw:b1r02j9)* status: 0 of 1 LGTMs obtained (waiting on @IanTheEngineer)

**Review by ggould-tri — COMMENTED** [review]
Okay, this now has enough retry logic to actually fix things, so I think it is worth reviewing.
The `_send_request` function is the retry logic; the ` _handle_any_error` function is the additional logging.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-:-O6wGpFz43WVIH-5PxA7:b-ybzc7i)* status: 0 of 1 LGTMs obtained (waiting on @IanTheEngineer)

**Review by ggould-tri — COMMENTED** [review]
-@IanTheEngineer +@sammy-tri 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-:-O6wVfZeAFCRaoCZqu_e:bdtemru)* status: 0 of 1 LGTMs obtained (waiting on @sammy-tri)

**Review by sammy-tri — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31)* status: 0 of 1 LGTMs obtained

___
*[`bazel_external_data/backends/http.py` line 86 at r1](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-O6wXyfHA8cLeWlF1eIb:-O6wXyfHA8cLeWlF1eIc:buds8) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/21dfc4779dbfd3ae913b1d447c170556f58a6467/bazel_external_data/backends/http.py#L86)):*
> ```Python
>             delay = 0.2
>             backoff_multiplier = 1.8
>             # Max delay: delay * multiplier ** (retries - 1)
> ```

A 71 second delay (after waiting out a 39 second delay) before going on to the next session seems annoying, at least for an interactive user.  I would have aborted the build manually and retried before that was over.   (maybe that's fine?)

Or maybe we really do want to take this long of a break because a malfunctioning session might come back?

**Comment by ggould-tri** [comment]
*[`bazel_external_data/backends/http.py` line 86 at r1](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-O6wXyfHA8cLeWlF1eIb:-O7-W2Hm1ZrqrEm9ZBge:bpajnxt) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/21dfc4779dbfd3ae913b1d447c170556f58a6467/bazel_external_data/backends/http.py#L86)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

A 71 second delay (after waiting out a 39 second delay) before going on to the next session seems annoying, at least for an interactive user.  I would have aborted the build manually and retried before that was over.   (maybe that's fine?)

Or maybe we really do want to take this long of a break because a malfunctioning session might come back?
</blockquote></details>

I have seen the server come back to life after ten minutes of retries; there isn't really a firm line.  The question is "at what point would a user prefer an error to a slow build" (these delays don't stack because the fetches are essentially always parallel rather than serial and are the ~last thing running in the build).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31)* status: 0 of 1 LGTMs obtained (waiting on @sammy-tri)

___
*[`bazel_external_data/backends/http.py` line 86 at r1](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-O6wXyfHA8cLeWlF1eIb:-O7-WuCJEH_qjq6R-roK:bgnkjpa) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/21dfc4779dbfd3ae913b1d447c170556f58a6467/bazel_external_data/backends/http.py#L86)):*
> The question is "at what point would a user prefer an error to a slow build"

My 2c:
* Locally?  30 seconds.
* In Anzu CI?  300 seconds.

**Review by sammy-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-:-O709A6s1G3ZO5-Oz4Tl:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

___
*[`bazel_external_data/backends/http.py` line 86 at r1](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-O6wXyfHA8cLeWlF1eIb:-O70807_7nrn5RwQbIVx:b-4q3822) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/21dfc4779dbfd3ae913b1d447c170556f58a6467/bazel_external_data/backends/http.py#L86)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> The question is "at what point would a user prefer an error to a slow build"

My 2c:
* Locally?  30 seconds.
* In Anzu CI?  300 seconds.
</blockquote></details>

I think my specific question was more around if there is a situation when the  session retry is likely to work, but it's not attempted for several minutes (and the holdup could have been resolved quickly). 

I guess you could increase the backoff by doing something like `retries = 11 / (session_retries + 1)` if you were interested in that kind of thing.

Anyway, I'm going to take myself off of "blocking" since this PR is a strict improvement over how things are now.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

___
*[`bazel_external_data/backends/http.py` line 86 at r1](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/31#-O6wXyfHA8cLeWlF1eIb:-O75QnxU83x28gWbbUPo:b-wjaeti) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/21dfc4779dbfd3ae913b1d447c170556f58a6467/bazel_external_data/backends/http.py#L86)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I think my specific question was more around if there is a situation when the  session retry is likely to work, but it's not attempted for several minutes (and the holdup could have been resolved quickly). 

I guess you could increase the backoff by doing something like `retries = 11 / (session_retries + 1)` if you were interested in that kind of thing.

Anyway, I'm going to take myself off of "blocking" since this PR is a strict improvement over how things are now.
</blockquote></details>

Yeah, I think I'll hold off on constant tuning until we have an idea of behaviour in the wild when there's sane caching (i.e., until someone complains with current code)

**Pull request merged**
