### PR TITLE
Add support for http put/get backend (such as s3)

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30)

### CODE REVIEW

**Comment by ggould-tri** [comment]
FYI @sammy-tri

**Review by ggould-tri — COMMENTED** [review]
+@sammy-tri This is now ready for review.  Note that I have removed references to S3, as this is in fact generic over http PUT/GET operations generally, as I discovered when writing the mock for the test.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-:-O6N1n-p1ZeGADHsAqez:bb2yo7j)* status: 0 of 1 LGTMs obtained (waiting on @sammy-tri)

**Review by ggould-tri — COMMENTED** [review]
-@sammy-tri Sammy is out.
+@IanTheEngineer Ian will step in instead.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-:-O6ReY8hAH8MI2rc6fil:b-i0nf2q)* status: 0 of 1 LGTMs obtained (waiting on @IanTheEngineer)

**Review by sammy-tri — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 1 of 4 files at r2, 5 of 7 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30)* status: 0 of 1 LGTMs obtained (waiting on @IanTheEngineer)

___
*[`bazel_external_data/backends/test/http_test.py` line 69 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6SER2XD27AhHxGFHwi:-O6SER2XD27AhHxGFHwj:b73owoh) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/test/http_test.py#L69)):*
> ```Python
>         server_address = ("127.0.0.1", 0)
>         self.server = MockHttp.Server(server_address,
>                                     RequestHandlerClass=MockHttp.Handler)
> ```

nit: indentation looks like it's off by one space
___
*[`bazel_external_data/backends/http.py` line 53 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6SBmxO-_JCV6LCaTHp:-O6SBmxO-_JCV6LCaTHq:b-c7ee6w) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/http.py#L53)):*
> ```Python
>             self._api_key = util.get_chain(url_config_node, ['api_key'])
>         else:
>             self._api_key = config['api-key']
> ```

Is there a reason why this one config variable uses a dash instead of an underscore?
___
*[`bazel_external_data/backends/http.py` line 72 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6SCurv6DWOdoYWvQQS:-O6SCurv6DWOdoYWvQQT:bnq7hsv) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/http.py#L72)):*
> ```Python
>     def _object_path(self, hash):
>         hash_path = ("" if hash.get_algo() == "sha512"
>                      else f"{hash.get_value()}/")
> ```

I'm confused...  this is for a case where we use an algorithm other than sha512, where we make a directory for every file and then put an identically named file in it?

**Review by IanTheEngineer — APPROVED** [review]
First pass done. Things look good so far to me. I'm in the middle of testing with Anzu and will report back once that's completed.

> Reviewed 3 of 7 files at r1, 1 of 4 files at r2, 5 of 7 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-:-O6SK2oe1pzFHAG-1Maz:be6b4rz)* status: 0 of 1 LGTMs obtained (waiting on @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6SBnfa1Js2-QQCq46l:-O6SBnfbAvQg0GqaNJe4:b-pigtlg) (no related file):*
Nit: Consider changing the name of this PR as well, since it's no longer S3 specific.

___
___
*[`.bazelrc` line 4 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6RjlpNB2rG2XhiUffZ:-O6RjlpNB2rG2XhiUff_:b-215td6) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/.bazelrc#L4)):*
> ```
> try-import %workspace%/user.bazelrc
> 
> common --enable_bzlmod=false
> ```

Nit: A comment as to why this is required would be appreciated, perhaps adding a TODO as your comment message give the impression that `bzlmod` support may be added in the future.
___
*[`bazel_external_data/backends/test/http_test.py` line 68 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6S3lTB5yWPZviJMibG:-O6S3lTB5yWPZviJMibH:b-a7lk4x) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/test/http_test.py#L68)):*
> ```Python
>         assert self.server is None
>         server_address = ("127.0.0.1", 0)
>         self.server = MockHttp.Server(server_address,
> ```

Nit: Odd indentation for the continued line.
___
*[`bazel_external_data/backends/test/http_test.py` line 140 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6S9j6v0TdKmJcS943K:-O6S9j6v0TdKmJcS943L:bva3u8t) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/test/http_test.py#L140)):*
> ```Python
> 
>     def _make_filename(self):
>         filename = f"test_data_{self.id()}.txt"
> ```

BTW: Using the [id function](https://docs.python.org/3/library/unittest.html#unittest.TestCase.id) of the test to create a unique filename is quite interesting. I have not thought to do this before.
___
*[`bazel_external_data/backends/test/http_test.py` line 190 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6S5dR36ylUTIaOHaTK:-O6S5dR36ylUTIaOHaTL:byebedi) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/test/http_test.py#L190)):*
> ```Python
>         with open(local_file, 'w') as test_data_file:
>             test_data_file.write(f"Test data: {filename}.\n")
>         hash = hashes.sha512.compute(local_file)
> ```

Nit: By using `hash` as a variable name, you're shadowing [Python's hash() function](https://docs.python.org/3/library/functions.html#hash). Consider renaming this variable slightly to disambiguate and avoid confusion.
___
*[`test/external_data_pkg_test/.bazelrc` line 4 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6Rj6R58jsjwU1AODQi:-O6Rj6R58jsjwU1AODQj:b-5eziyl) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/test/external_data_pkg_test/.bazelrc#L4)):*
> ```
> try-import %workspace%/user.bazelrc
> 
> common --enable_bzlmod=false
> ```

Nit: Same as the above: A comment and / or a TODO describing the `bzlmod` opt-out would be appreciated.

**Review by IanTheEngineer — APPROVED** [review]
:LGTM: After running `bazel clean --expunge` and removing the local bazel cache, I re-ran tests on the Anzu side and the tests passed. Things look good as far as I can tell, and CI appears happy. Thanks for all your work here, Grant!

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-:-O6SZ7Sp0lhgKmMyJGWu:baltu0x)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

___
*[`bazel_external_data/backends/test/http_test.py` line 140 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6S9j6v0TdKmJcS943K:-O6SUwu1846mKHa4g_kX:bhu07lx) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/test/http_test.py#L140)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

BTW: Using the [id function](https://docs.python.org/3/library/unittest.html#unittest.TestCase.id) of the test to create a unique filename is quite interesting. I have not thought to do this before.
</blockquote></details>

Yeah, I didn't think of it for a long time either.  Beat my head against copypasta errors.  :-)
___
*[`bazel_external_data/backends/http.py` line 53 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6SBmxO-_JCV6LCaTHp:-O6SIT1jBma9QQHCnBkh:b-oamifx) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/http.py#L53)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

Is there a reason why this one config variable uses a dash instead of an underscore?
</blockquote></details>

Facepalm emoji.
I was copypasta'ing from some python docs in the dumbest way.
___
*[`bazel_external_data/backends/http.py` line 72 at r5](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-O6SCurv6DWOdoYWvQQS:-O6SOZOb985Hs-RufhT3:b-hjyams) ([raw file](https://github.com/RobotLocomotion/bazel-external-data/blob/74e9b27311a8df60361eb16869488275626f39ef/bazel_external_data/backends/http.py#L72)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

I'm confused...  this is for a case where we use an algorithm other than sha512, where we make a directory for every file and then put an identically named file in it?
</blockquote></details>

Yeah, this was wrong, it was meant to put files into algo directories to mimic what girder (`girder.py`:124) does, but to not do so with sha512 because Ramya didn't prefix hash algorithm onto the front.  I think this typo is now fixed.

**Review by sammy-tri — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/bazel-external-data/30#-:-O6SegYz3zZCm7iswxFL:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
