### PR TITLE
Add external_data_repository_download

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
@hidmic Would you be for (informally) reviewing this? (in relation to Anzu changes)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-:-MwYC1jS3npKFk98RN0f:bh8ssqk)* status: 0 of 1 LGTMs obtained

**Review by hidmic — COMMENTED** [review]
Overall LGTM, but for a few minor comments

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-:-MwcLJtH55531swH5P8O:b-i48ew4)* status: 0 of 1 LGTMs obtained

___
*[.bazelrc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcACy4E1MSczq53hGf:-MwcACy4E1MSczq53hGg:b-hnwove) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/.bazelrc#L5)):*
> ```
> 
> test --test_output=errors
> test --test_summary=terse
> ```

nit: fine with making `bazel test` a bit more verbose, but why drop them for `bazel build`?
___
*[.external_data_cli_proxy.py, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcAoZi6SahCD6e275j:-MwcAoZi6SahCD6e275k:b-e4j1hs) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/.external_data_cli_proxy.py#L3)):*
> ```Python
> #!/usr/bin/env python3
> 
> # Provides a mechanism to provide a subset of `//:cli` functionality to
> ```

nit: `Provides a mechanism to provide` -> `Provides a mechanism to expose` 
___
*[external_data.bzl, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcBGMeD2tqfcJrWeVe:-MwcBGMeD2tqfcJrWeVf:b-g4nftg) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/e722493c18eb9c111e1b6fcee722a5dbdb6af9be/external_data.bzl#L18)):*
> ```Starlark
>     # but can be changed.
>     # @note This is NOT for arguments after `cli ... download`.
>     cli_extra_args = [],
> ```

nit unrelated feature drop?
___
*[external_data.bzl, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcKsvC4hY2dOkSG8pq:-MwcKsvC4hY2dOkSG8pr:b-3iwtt2) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/external_data.bzl#L427)):*
> ```Starlark
>         settings=SETTINGS_DEFAULT,
>         python_bin="/usr/bin/python3",
>     ):
> ```

nit: for consistency with the rest of this source file, consider leaving the parenthesis at the end of the previous line
___
*[test/external_data_pkg_test/test_basics.py, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcKPOSB6vLJZKaGflK:-MwcKPOTCW1s49oMotaP:b5ojcnz) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/test/external_data_pkg_test/test_basics.py#L75)):*
> ```Python
>                 c = f.read()
>                 expected = "Content for '{}'\n".format(basename(file))
>                 assert c == expected, c
> ```

nit: this is a `unittest` test case, consider using `self.assertEqual()` instead.

**Review by hidmic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)* status: 0 of 1 LGTMs obtained

___
*[test/external_data_pkg_test/repo_example.bzl, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-Mwc_IjbBupt-3NILVGN:-Mwc_Ijc5ruzcLGvT40l:bn98mt3) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/test/external_data_pkg_test/repo_example.bzl#L19)):*
> ```Starlark
>     # N.B. This will complain about not having a SHA256. Consider just using
>     # `tar` or direct command line?
>     repo_ctx.download_and_extract(
> ```

Also, why not use https://docs.bazel.build/versions/main/skylark/lib/repository_ctx.html#extract instead?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)* status: 0 of 1 LGTMs obtained

___
*[.bazelrc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcACy4E1MSczq53hGf:-MwchMZJ85kUKQ0sSf2w:b39yp94) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/.bazelrc#L5)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

nit: fine with making `bazel test` a bit more verbose, but why drop them for `bazel build`?
</blockquote></details>

Hm... which are the equivalent flags for a `build`?
___
*[.external_data_cli_proxy.py, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcAoZi6SahCD6e275j:-MwciVjh7cJkeZ0ibPgA:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/.external_data_cli_proxy.py#L3)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

nit: `Provides a mechanism to provide` -> `Provides a mechanism to expose` 
</blockquote></details>

Done.
___
*[external_data.bzl, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcBGMeD2tqfcJrWeVe:-MwciWQS1TDrpRQJHdN3:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/e722493c18eb9c111e1b6fcee722a5dbdb6af9be/external_data.bzl#L18)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

nit unrelated feature drop?
</blockquote></details>

Done.
___
*[external_data.bzl, line 427 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcKsvC4hY2dOkSG8pq:-MwciX0UCyV8h5fGewb6:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/external_data.bzl#L427)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

nit: for consistency with the rest of this source file, consider leaving the parenthesis at the end of the previous line
</blockquote></details>

Done.
___
*[test/external_data_pkg_test/repo_example.bzl, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-Mwc_IjbBupt-3NILVGN:-MwciXr7EiHTYn4ca0ZX:bsckazj) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/test/external_data_pkg_test/repo_example.bzl#L19)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Also, why not use https://docs.bazel.build/versions/main/skylark/lib/repository_ctx.html#extract instead?
</blockquote></details>

Done. Ooh, didn't see that!
(not sure if it was around ~3 years ago)
___
*[test/external_data_pkg_test/test_basics.py, line 75 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcKPOSB6vLJZKaGflK:-Mwci_xQ5e2XCihF6ETz:b-hatmc8) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/test/external_data_pkg_test/test_basics.py#L75)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

nit: this is a `unittest` test case, consider using `self.assertEqual()` instead.
</blockquote></details>

Done - good point!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)* status: 0 of 1 LGTMs obtained

___
*[.bazelrc, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcACy4E1MSczq53hGf:-MwcjJ6uAQ6cYS_X8L13:b-dsl7kc) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/fa4cd8b8cd93a00f2102888369cbac601410c43c/.bazelrc#L5)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... which are the equivalent flags for a `build`?
</blockquote></details>

OK Ah, it's what Anzu uses.

For contrast, Drake uses `test`, but meh. Thanks!

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-Mwcl0Jp2Ga22QXGRxVJ:-Mwcl0Jp2Ga22QXGRxVK:b-iodbgz) (no related file):*
Working: Should ensure full CI passes for Anzu PR 8460 w/ these changes. (I pared down testing for this specific feature for integ.)

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)* status: 0 of 1 LGTMs obtained

___
*[external_data.bzl, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcBGMeD2tqfcJrWeVe:-MwcmIld2BvtolU-565T:b-rcfb7d) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/e722493c18eb9c111e1b6fcee722a5dbdb6af9be/external_data.bzl#L18)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK Ah - forgot to say - the drop was intentional. I updated commit message.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)* status: 0 of 1 LGTMs obtained

___
*[external_data.bzl, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcqHaZ270_B92yBifH:-MwcqHaZ270_B92yBifI:b-mvzn3l) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/41bd2c692f017bc2348a1c612193384b59d56c2b/external_data.bzl#L7)):*
> ```Starlark
>     # keys!).
>     verbose = False,
>     # Sentinel data. Used to detect the project root.
> ```

Working: For repository usage, should mention that this should be a file label, not an abstract (filegroup) target.

(same for sentinel below)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks! I'm gonna go ahead and merge!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-:-MwcuLsk5w93COoH2bR-:bwhuupw)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-Mwcl0Jp2Ga22QXGRxVJ:-MwcuJh_DL1b7SjUfHKf:b-ep2ou0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should ensure full CI passes for Anzu PR 8460 w/ these changes. (I pared down testing for this specific feature for integ.)
</blockquote></details>

OK Full CI passed w/ these changes.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)* status: 0 of 1 LGTMs obtained

___
*[external_data.bzl, line 7 at r3](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-MwcqHaZ270_B92yBifH:-MwcvFr46-7gUssVlY0S:b-896fix) ([raw file](https://github.com/robotlocomotion/bazel-external-data/blob/41bd2c692f017bc2348a1c612193384b59d56c2b/external_data.bzl#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: For repository usage, should mention that this should be a file label, not an abstract (filegroup) target.

(same for sentinel below)
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
Adding self-stamp as proxy for Miche's approval: +@ericcousineau-tri :lgtm:

> Dismissed @hidmic from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8#-:-Mwcvo6SEr6aSUYMkTIy:b840ez0)* status: 0 of 1 LGTMs obtained, and 1 stale (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/bazel-external-data/8)* status: 0 of 1 LGTMs obtained, and 1 stale (waiting on @EricCousineau-TRI)

**Comment by EricCousineau-TRI** [comment]
Hm, not sure about Reviewable interlock, but meh. Onwards!

**Pull request merged**
